/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_byte_order_mark = 1,
  sym_webvtt_keyword = 2,
  sym_region_keyword = 3,
  sym_style_keyword = 4,
  sym_note_keyword = 5,
  sym_id_attribute = 6,
  sym_width_attribute = 7,
  sym_lines_attribute = 8,
  sym_region_anchor_attribute = 9,
  sym_viewport_anchor_attribute = 10,
  sym_scroll_attribute = 11,
  sym_cue_setting_item = 12,
  sym_separator_colon = 13,
  sym_tab_separator = 14,
  sym_space_separator = 15,
  sym_tabs_or_spaces = 16,
  sym__line_terminator = 17,
  sym_timestamp = 18,
  sym_timestamp_arrow = 19,
  sym_line_without_arrow = 20,
  sym_cue_name = 21,
  sym_source_file = 22,
  sym__group1 = 23,
  sym__group2 = 24,
  sym_webvtt_block = 25,
  sym_region_definition_block = 26,
  sym_region_identifier = 27,
  sym_region_width = 28,
  sym_region_lines = 29,
  sym_region_anchor = 30,
  sym_region_viewport_anchor = 31,
  sym_region_scroll = 32,
  sym_comment_block = 33,
  sym_style_block = 34,
  sym_cue_block = 35,
  sym_cue_settings = 36,
  sym_cue_setting = 37,
  sym_timestamp_range_line = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_source_file_repeat2 = 40,
  aux_sym_source_file_repeat3 = 41,
  aux_sym_region_definition_block_repeat1 = 42,
  aux_sym_comment_block_repeat1 = 43,
  aux_sym_cue_settings_repeat1 = 44,
  aux_sym_timestamp_range_line_repeat1 = 45,
  aux_sym_timestamp_range_line_repeat2 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_byte_order_mark] = "byte_order_mark",
  [sym_webvtt_keyword] = "webvtt_keyword",
  [sym_region_keyword] = "region_keyword",
  [sym_style_keyword] = "style_keyword",
  [sym_note_keyword] = "note_keyword",
  [sym_id_attribute] = "id_attribute",
  [sym_width_attribute] = "width_attribute",
  [sym_lines_attribute] = "lines_attribute",
  [sym_region_anchor_attribute] = "region_anchor_attribute",
  [sym_viewport_anchor_attribute] = "viewport_anchor_attribute",
  [sym_scroll_attribute] = "scroll_attribute",
  [sym_cue_setting_item] = "cue_setting_item",
  [sym_separator_colon] = "separator_colon",
  [sym_tab_separator] = "tab_separator",
  [sym_space_separator] = "space_separator",
  [sym_tabs_or_spaces] = "tabs_or_spaces",
  [sym__line_terminator] = "_line_terminator",
  [sym_timestamp] = "timestamp",
  [sym_timestamp_arrow] = "timestamp_arrow",
  [sym_line_without_arrow] = "line_without_arrow",
  [sym_cue_name] = "cue_name",
  [sym_source_file] = "source_file",
  [sym__group1] = "_group1",
  [sym__group2] = "_group2",
  [sym_webvtt_block] = "webvtt_block",
  [sym_region_definition_block] = "region_definition_block",
  [sym_region_identifier] = "region_identifier",
  [sym_region_width] = "region_width",
  [sym_region_lines] = "region_lines",
  [sym_region_anchor] = "region_anchor",
  [sym_region_viewport_anchor] = "region_viewport_anchor",
  [sym_region_scroll] = "region_scroll",
  [sym_comment_block] = "comment_block",
  [sym_style_block] = "style_block",
  [sym_cue_block] = "cue_block",
  [sym_cue_settings] = "cue_settings",
  [sym_cue_setting] = "cue_setting",
  [sym_timestamp_range_line] = "timestamp_range_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_source_file_repeat3] = "source_file_repeat3",
  [aux_sym_region_definition_block_repeat1] = "region_definition_block_repeat1",
  [aux_sym_comment_block_repeat1] = "comment_block_repeat1",
  [aux_sym_cue_settings_repeat1] = "cue_settings_repeat1",
  [aux_sym_timestamp_range_line_repeat1] = "timestamp_range_line_repeat1",
  [aux_sym_timestamp_range_line_repeat2] = "timestamp_range_line_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_byte_order_mark] = sym_byte_order_mark,
  [sym_webvtt_keyword] = sym_webvtt_keyword,
  [sym_region_keyword] = sym_region_keyword,
  [sym_style_keyword] = sym_style_keyword,
  [sym_note_keyword] = sym_note_keyword,
  [sym_id_attribute] = sym_id_attribute,
  [sym_width_attribute] = sym_width_attribute,
  [sym_lines_attribute] = sym_lines_attribute,
  [sym_region_anchor_attribute] = sym_region_anchor_attribute,
  [sym_viewport_anchor_attribute] = sym_viewport_anchor_attribute,
  [sym_scroll_attribute] = sym_scroll_attribute,
  [sym_cue_setting_item] = sym_cue_setting_item,
  [sym_separator_colon] = sym_separator_colon,
  [sym_tab_separator] = sym_tab_separator,
  [sym_space_separator] = sym_space_separator,
  [sym_tabs_or_spaces] = sym_tabs_or_spaces,
  [sym__line_terminator] = sym__line_terminator,
  [sym_timestamp] = sym_timestamp,
  [sym_timestamp_arrow] = sym_timestamp_arrow,
  [sym_line_without_arrow] = sym_line_without_arrow,
  [sym_cue_name] = sym_cue_name,
  [sym_source_file] = sym_source_file,
  [sym__group1] = sym__group1,
  [sym__group2] = sym__group2,
  [sym_webvtt_block] = sym_webvtt_block,
  [sym_region_definition_block] = sym_region_definition_block,
  [sym_region_identifier] = sym_region_identifier,
  [sym_region_width] = sym_region_width,
  [sym_region_lines] = sym_region_lines,
  [sym_region_anchor] = sym_region_anchor,
  [sym_region_viewport_anchor] = sym_region_viewport_anchor,
  [sym_region_scroll] = sym_region_scroll,
  [sym_comment_block] = sym_comment_block,
  [sym_style_block] = sym_style_block,
  [sym_cue_block] = sym_cue_block,
  [sym_cue_settings] = sym_cue_settings,
  [sym_cue_setting] = sym_cue_setting,
  [sym_timestamp_range_line] = sym_timestamp_range_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_source_file_repeat3] = aux_sym_source_file_repeat3,
  [aux_sym_region_definition_block_repeat1] = aux_sym_region_definition_block_repeat1,
  [aux_sym_comment_block_repeat1] = aux_sym_comment_block_repeat1,
  [aux_sym_cue_settings_repeat1] = aux_sym_cue_settings_repeat1,
  [aux_sym_timestamp_range_line_repeat1] = aux_sym_timestamp_range_line_repeat1,
  [aux_sym_timestamp_range_line_repeat2] = aux_sym_timestamp_range_line_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_byte_order_mark] = {
    .visible = true,
    .named = true,
  },
  [sym_webvtt_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_region_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_style_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_note_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_id_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_width_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_lines_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_region_anchor_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_viewport_anchor_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_scroll_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_setting_item] = {
    .visible = true,
    .named = true,
  },
  [sym_separator_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_tab_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_space_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_tabs_or_spaces] = {
    .visible = true,
    .named = true,
  },
  [sym__line_terminator] = {
    .visible = false,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_line_without_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_name] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__group1] = {
    .visible = false,
    .named = true,
  },
  [sym__group2] = {
    .visible = false,
    .named = true,
  },
  [sym_webvtt_block] = {
    .visible = true,
    .named = true,
  },
  [sym_region_definition_block] = {
    .visible = true,
    .named = true,
  },
  [sym_region_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_region_width] = {
    .visible = true,
    .named = true,
  },
  [sym_region_lines] = {
    .visible = true,
    .named = true,
  },
  [sym_region_anchor] = {
    .visible = true,
    .named = true,
  },
  [sym_region_viewport_anchor] = {
    .visible = true,
    .named = true,
  },
  [sym_region_scroll] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym_style_block] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_block] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_settings] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp_range_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_region_definition_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cue_settings_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_timestamp_range_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_timestamp_range_line_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 20,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(79);
      ADVANCE_MAP(
        '-', 7,
        ':', 94,
        'N', 24,
        'R', 14,
        'S', 25,
        'W', 17,
        'i', 36,
        'l', 45,
        'r', 38,
        's', 33,
        'v', 47,
        'w', 46,
        0xefbb, 12,
        0xfeff, 80,
        0xfffe, 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(95);
      if (lookahead == ' ') ADVANCE(98);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(96);
      if (lookahead == '-') ADVANCE(7);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(104);
      if (lookahead == '\r') ADVANCE(104);
      if (lookahead == ' ') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(100);
      if (lookahead == '-') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(77);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(77);
      if (lookahead == ':') ADVANCE(75);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(74);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(107);
      END_STATE();
    case 12:
      if (lookahead == 'B') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'B') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(84);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(83);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'F') ADVANCE(80);
      END_STATE();
    case 19:
      if (lookahead == 'G') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 'I') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'N') ADVANCE(82);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'T') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'T') ADVANCE(81);
      END_STATE();
    case 27:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 28:
      if (lookahead == 'T') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 'V') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 'Y') ADVANCE(21);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(85);
      END_STATE();
    case 37:
      if (lookahead == 'd') ADVANCE(66);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 41:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 42:
      if (lookahead == 'h') ADVANCE(86);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(58);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(59);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(63);
      END_STATE();
    case 60:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(89);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(87);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 68:
      if (lookahead == 'w') ADVANCE(60);
      END_STATE();
    case 69:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(92);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(69);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 73:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 74:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 75:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 78:
      if (eof) ADVANCE(79);
      ADVANCE_MAP(
        '\n', 103,
        '\r', 103,
        'N', 24,
        'R', 14,
        'S', 25,
        'i', 36,
        'l', 45,
        'r', 38,
        's', 33,
        'v', 47,
        'w', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_byte_order_mark);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_webvtt_keyword);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_region_keyword);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_style_keyword);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_note_keyword);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_id_attribute);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_width_attribute);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_lines_attribute);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_region_anchor_attribute);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_viewport_anchor_attribute);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_scroll_attribute);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_cue_setting_item);
      if (lookahead == '\n') ADVANCE(104);
      if (lookahead == '\r') ADVANCE(104);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_cue_setting_item);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_cue_setting_item);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_separator_colon);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_tab_separator);
      if (lookahead == '\t') ADVANCE(95);
      if (lookahead == ' ') ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_tab_separator);
      if (lookahead == '\t') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_tab_separator);
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_space_separator);
      if (lookahead == '\t') ADVANCE(95);
      if (lookahead == ' ') ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_space_separator);
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_space_separator);
      if (lookahead == ' ') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_tabs_or_spaces);
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__line_terminator);
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__line_terminator);
      if (lookahead == '\n') ADVANCE(103);
      if (lookahead == '\r') ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym__line_terminator);
      if (lookahead == '\n') ADVANCE(104);
      if (lookahead == '\r') ADVANCE(104);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(91);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym__line_terminator);
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_timestamp);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_timestamp_arrow);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 78, .external_lex_state = 2},
  [3] = {.lex_state = 78, .external_lex_state = 2},
  [4] = {.lex_state = 78},
  [5] = {.lex_state = 78},
  [6] = {.lex_state = 78},
  [7] = {.lex_state = 78},
  [8] = {.lex_state = 78},
  [9] = {.lex_state = 78, .external_lex_state = 2},
  [10] = {.lex_state = 78, .external_lex_state = 2},
  [11] = {.lex_state = 78, .external_lex_state = 2},
  [12] = {.lex_state = 78, .external_lex_state = 2},
  [13] = {.lex_state = 78, .external_lex_state = 2},
  [14] = {.lex_state = 78, .external_lex_state = 2},
  [15] = {.lex_state = 78, .external_lex_state = 2},
  [16] = {.lex_state = 78, .external_lex_state = 2},
  [17] = {.lex_state = 78, .external_lex_state = 2},
  [18] = {.lex_state = 78, .external_lex_state = 2},
  [19] = {.lex_state = 78, .external_lex_state = 2},
  [20] = {.lex_state = 78, .external_lex_state = 2},
  [21] = {.lex_state = 78, .external_lex_state = 2},
  [22] = {.lex_state = 78, .external_lex_state = 2},
  [23] = {.lex_state = 78, .external_lex_state = 2},
  [24] = {.lex_state = 78, .external_lex_state = 2},
  [25] = {.lex_state = 78, .external_lex_state = 2},
  [26] = {.lex_state = 78},
  [27] = {.lex_state = 78},
  [28] = {.lex_state = 78, .external_lex_state = 2},
  [29] = {.lex_state = 78, .external_lex_state = 2},
  [30] = {.lex_state = 78},
  [31] = {.lex_state = 78, .external_lex_state = 2},
  [32] = {.lex_state = 78, .external_lex_state = 2},
  [33] = {.lex_state = 78, .external_lex_state = 2},
  [34] = {.lex_state = 78, .external_lex_state = 2},
  [35] = {.lex_state = 78},
  [36] = {.lex_state = 78},
  [37] = {.lex_state = 78},
  [38] = {.lex_state = 78, .external_lex_state = 2},
  [39] = {.lex_state = 78, .external_lex_state = 2},
  [40] = {.lex_state = 78, .external_lex_state = 2},
  [41] = {.lex_state = 78, .external_lex_state = 2},
  [42] = {.lex_state = 78, .external_lex_state = 2},
  [43] = {.lex_state = 78, .external_lex_state = 2},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 78, .external_lex_state = 3},
  [49] = {.lex_state = 78},
  [50] = {.lex_state = 78, .external_lex_state = 3},
  [51] = {.lex_state = 78, .external_lex_state = 3},
  [52] = {.lex_state = 78, .external_lex_state = 3},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 78, .external_lex_state = 3},
  [57] = {.lex_state = 78, .external_lex_state = 3},
  [58] = {.lex_state = 78},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 78, .external_lex_state = 3},
  [62] = {.lex_state = 78, .external_lex_state = 3},
  [63] = {.lex_state = 78, .external_lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 78},
  [66] = {.lex_state = 78, .external_lex_state = 3},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 78},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 78, .external_lex_state = 3},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 0, .external_lex_state = 3},
  [77] = {.lex_state = 0, .external_lex_state = 3},
  [78] = {.lex_state = 0, .external_lex_state = 3},
  [79] = {.lex_state = 0, .external_lex_state = 3},
  [80] = {.lex_state = 78},
  [81] = {.lex_state = 0, .external_lex_state = 3},
  [82] = {.lex_state = 0, .external_lex_state = 3},
  [83] = {.lex_state = 78},
  [84] = {.lex_state = 78},
  [85] = {.lex_state = 78},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 69},
  [88] = {.lex_state = 0, .external_lex_state = 3},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 78},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 78},
  [96] = {.lex_state = 0, .external_lex_state = 3},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_byte_order_mark] = ACTIONS(1),
    [sym_webvtt_keyword] = ACTIONS(1),
    [sym_region_keyword] = ACTIONS(1),
    [sym_style_keyword] = ACTIONS(1),
    [sym_note_keyword] = ACTIONS(1),
    [sym_id_attribute] = ACTIONS(1),
    [sym_width_attribute] = ACTIONS(1),
    [sym_lines_attribute] = ACTIONS(1),
    [sym_region_anchor_attribute] = ACTIONS(1),
    [sym_viewport_anchor_attribute] = ACTIONS(1),
    [sym_scroll_attribute] = ACTIONS(1),
    [sym_separator_colon] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
    [sym_timestamp_arrow] = ACTIONS(1),
    [sym_line_without_arrow] = ACTIONS(1),
    [sym_cue_name] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(97),
    [sym_webvtt_block] = STATE(2),
    [sym_byte_order_mark] = ACTIONS(3),
    [sym_webvtt_keyword] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      sym_region_keyword,
    ACTIONS(11), 1,
      sym_style_keyword,
    ACTIONS(13), 1,
      sym_note_keyword,
    ACTIONS(15), 1,
      sym__line_terminator,
    ACTIONS(17), 1,
      sym_timestamp,
    ACTIONS(19), 1,
      sym_cue_name,
    STATE(11), 1,
      aux_sym_source_file_repeat2,
    STATE(70), 1,
      sym_timestamp_range_line,
    STATE(10), 3,
      sym__group2,
      sym_cue_block,
      aux_sym_source_file_repeat3,
    STATE(3), 5,
      sym__group1,
      sym_region_definition_block,
      sym_comment_block,
      sym_style_block,
      aux_sym_source_file_repeat1,
  [40] = 11,
    ACTIONS(9), 1,
      sym_region_keyword,
    ACTIONS(11), 1,
      sym_style_keyword,
    ACTIONS(13), 1,
      sym_note_keyword,
    ACTIONS(17), 1,
      sym_timestamp,
    ACTIONS(19), 1,
      sym_cue_name,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym__line_terminator,
    STATE(12), 1,
      aux_sym_source_file_repeat2,
    STATE(70), 1,
      sym_timestamp_range_line,
    STATE(13), 3,
      sym__group2,
      sym_cue_block,
      aux_sym_source_file_repeat3,
    STATE(9), 5,
      sym__group1,
      sym_region_definition_block,
      sym_comment_block,
      sym_style_block,
      aux_sym_source_file_repeat1,
  [80] = 8,
    ACTIONS(25), 1,
      sym_id_attribute,
    ACTIONS(27), 1,
      sym_width_attribute,
    ACTIONS(29), 1,
      sym_lines_attribute,
    ACTIONS(31), 1,
      sym_region_anchor_attribute,
    ACTIONS(33), 1,
      sym_viewport_anchor_attribute,
    ACTIONS(35), 1,
      sym_scroll_attribute,
    ACTIONS(37), 1,
      sym__line_terminator,
    STATE(6), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [111] = 8,
    ACTIONS(25), 1,
      sym_id_attribute,
    ACTIONS(27), 1,
      sym_width_attribute,
    ACTIONS(29), 1,
      sym_lines_attribute,
    ACTIONS(31), 1,
      sym_region_anchor_attribute,
    ACTIONS(33), 1,
      sym_viewport_anchor_attribute,
    ACTIONS(35), 1,
      sym_scroll_attribute,
    ACTIONS(39), 1,
      sym__line_terminator,
    STATE(7), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [142] = 8,
    ACTIONS(25), 1,
      sym_id_attribute,
    ACTIONS(27), 1,
      sym_width_attribute,
    ACTIONS(29), 1,
      sym_lines_attribute,
    ACTIONS(31), 1,
      sym_region_anchor_attribute,
    ACTIONS(33), 1,
      sym_viewport_anchor_attribute,
    ACTIONS(35), 1,
      sym_scroll_attribute,
    ACTIONS(39), 1,
      sym__line_terminator,
    STATE(8), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [173] = 8,
    ACTIONS(25), 1,
      sym_id_attribute,
    ACTIONS(27), 1,
      sym_width_attribute,
    ACTIONS(29), 1,
      sym_lines_attribute,
    ACTIONS(31), 1,
      sym_region_anchor_attribute,
    ACTIONS(33), 1,
      sym_viewport_anchor_attribute,
    ACTIONS(35), 1,
      sym_scroll_attribute,
    ACTIONS(41), 1,
      sym__line_terminator,
    STATE(8), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [204] = 8,
    ACTIONS(43), 1,
      sym_id_attribute,
    ACTIONS(46), 1,
      sym_width_attribute,
    ACTIONS(49), 1,
      sym_lines_attribute,
    ACTIONS(52), 1,
      sym_region_anchor_attribute,
    ACTIONS(55), 1,
      sym_viewport_anchor_attribute,
    ACTIONS(58), 1,
      sym_scroll_attribute,
    ACTIONS(61), 1,
      sym__line_terminator,
    STATE(8), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [235] = 6,
    ACTIONS(65), 1,
      sym_region_keyword,
    ACTIONS(68), 1,
      sym_style_keyword,
    ACTIONS(71), 1,
      sym_note_keyword,
    ACTIONS(74), 1,
      sym_timestamp,
    ACTIONS(63), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    STATE(9), 5,
      sym__group1,
      sym_region_definition_block,
      sym_comment_block,
      sym_style_block,
      aux_sym_source_file_repeat1,
  [260] = 8,
    ACTIONS(13), 1,
      sym_note_keyword,
    ACTIONS(17), 1,
      sym_timestamp,
    ACTIONS(19), 1,
      sym_cue_name,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      sym__line_terminator,
    STATE(69), 1,
      aux_sym_source_file_repeat2,
    STATE(70), 1,
      sym_timestamp_range_line,
    STATE(15), 4,
      sym__group2,
      sym_comment_block,
      sym_cue_block,
      aux_sym_source_file_repeat3,
  [288] = 8,
    ACTIONS(13), 1,
      sym_note_keyword,
    ACTIONS(17), 1,
      sym_timestamp,
    ACTIONS(19), 1,
      sym_cue_name,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      sym__line_terminator,
    STATE(38), 1,
      aux_sym_source_file_repeat2,
    STATE(70), 1,
      sym_timestamp_range_line,
    STATE(13), 4,
      sym__group2,
      sym_comment_block,
      sym_cue_block,
      aux_sym_source_file_repeat3,
  [316] = 8,
    ACTIONS(13), 1,
      sym_note_keyword,
    ACTIONS(17), 1,
      sym_timestamp,
    ACTIONS(19), 1,
      sym_cue_name,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      sym__line_terminator,
    STATE(39), 1,
      aux_sym_source_file_repeat2,
    STATE(70), 1,
      sym_timestamp_range_line,
    STATE(14), 4,
      sym__group2,
      sym_comment_block,
      sym_cue_block,
      aux_sym_source_file_repeat3,
  [344] = 8,
    ACTIONS(13), 1,
      sym_note_keyword,
    ACTIONS(17), 1,
      sym_timestamp,
    ACTIONS(19), 1,
      sym_cue_name,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      sym__line_terminator,
    STATE(58), 1,
      aux_sym_source_file_repeat2,
    STATE(70), 1,
      sym_timestamp_range_line,
    STATE(15), 4,
      sym__group2,
      sym_comment_block,
      sym_cue_block,
      aux_sym_source_file_repeat3,
  [372] = 8,
    ACTIONS(13), 1,
      sym_note_keyword,
    ACTIONS(17), 1,
      sym_timestamp,
    ACTIONS(19), 1,
      sym_cue_name,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      sym__line_terminator,
    STATE(65), 1,
      aux_sym_source_file_repeat2,
    STATE(70), 1,
      sym_timestamp_range_line,
    STATE(15), 4,
      sym__group2,
      sym_comment_block,
      sym_cue_block,
      aux_sym_source_file_repeat3,
  [400] = 6,
    ACTIONS(92), 1,
      sym_note_keyword,
    ACTIONS(95), 1,
      sym_timestamp,
    ACTIONS(98), 1,
      sym_cue_name,
    STATE(70), 1,
      sym_timestamp_range_line,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      sym__line_terminator,
    STATE(15), 4,
      sym__group2,
      sym_comment_block,
      sym_cue_block,
      aux_sym_source_file_repeat3,
  [423] = 3,
    STATE(22), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(101), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(103), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [438] = 3,
    STATE(18), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(105), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(107), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [453] = 3,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(101), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(103), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [468] = 3,
    STATE(21), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(109), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(111), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [483] = 4,
    ACTIONS(117), 1,
      sym__line_terminator,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(113), 2,
      sym_cue_name,
      ts_builtin_sym_end,
    ACTIONS(115), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [500] = 3,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(120), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(122), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [515] = 3,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(109), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(111), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [530] = 3,
    STATE(24), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(120), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(122), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [545] = 3,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(124), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(126), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [560] = 2,
    ACTIONS(128), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(130), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [572] = 2,
    ACTIONS(134), 1,
      sym__line_terminator,
    ACTIONS(132), 6,
      sym_id_attribute,
      sym_width_attribute,
      sym_lines_attribute,
      sym_region_anchor_attribute,
      sym_viewport_anchor_attribute,
      sym_scroll_attribute,
  [584] = 2,
    ACTIONS(138), 1,
      sym__line_terminator,
    ACTIONS(136), 6,
      sym_id_attribute,
      sym_width_attribute,
      sym_lines_attribute,
      sym_region_anchor_attribute,
      sym_viewport_anchor_attribute,
      sym_scroll_attribute,
  [596] = 2,
    ACTIONS(140), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(142), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [608] = 2,
    ACTIONS(144), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(146), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [620] = 2,
    ACTIONS(150), 1,
      sym__line_terminator,
    ACTIONS(148), 6,
      sym_id_attribute,
      sym_width_attribute,
      sym_lines_attribute,
      sym_region_anchor_attribute,
      sym_viewport_anchor_attribute,
      sym_scroll_attribute,
  [632] = 2,
    ACTIONS(152), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(154), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [644] = 2,
    ACTIONS(156), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(158), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [656] = 2,
    ACTIONS(160), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(162), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [668] = 2,
    ACTIONS(164), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
    ACTIONS(166), 4,
      sym_region_keyword,
      sym_style_keyword,
      sym_note_keyword,
      sym_timestamp,
  [680] = 2,
    ACTIONS(170), 1,
      sym__line_terminator,
    ACTIONS(168), 6,
      sym_id_attribute,
      sym_width_attribute,
      sym_lines_attribute,
      sym_region_anchor_attribute,
      sym_viewport_anchor_attribute,
      sym_scroll_attribute,
  [692] = 2,
    ACTIONS(174), 1,
      sym__line_terminator,
    ACTIONS(172), 6,
      sym_id_attribute,
      sym_width_attribute,
      sym_lines_attribute,
      sym_region_anchor_attribute,
      sym_viewport_anchor_attribute,
      sym_scroll_attribute,
  [704] = 2,
    ACTIONS(178), 1,
      sym__line_terminator,
    ACTIONS(176), 6,
      sym_id_attribute,
      sym_width_attribute,
      sym_lines_attribute,
      sym_region_anchor_attribute,
      sym_viewport_anchor_attribute,
      sym_scroll_attribute,
  [716] = 5,
    ACTIONS(113), 1,
      sym_cue_name,
    ACTIONS(117), 1,
      sym__line_terminator,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(115), 2,
      sym_note_keyword,
      sym_timestamp,
  [733] = 5,
    ACTIONS(113), 1,
      sym_cue_name,
    ACTIONS(117), 1,
      sym__line_terminator,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(115), 2,
      sym_note_keyword,
      sym_timestamp,
  [750] = 2,
    ACTIONS(188), 2,
      sym_note_keyword,
      sym_timestamp,
    ACTIONS(186), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
  [760] = 2,
    ACTIONS(192), 2,
      sym_note_keyword,
      sym_timestamp,
    ACTIONS(190), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
  [770] = 2,
    ACTIONS(196), 2,
      sym_note_keyword,
      sym_timestamp,
    ACTIONS(194), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
  [780] = 2,
    ACTIONS(200), 2,
      sym_note_keyword,
      sym_timestamp,
    ACTIONS(198), 3,
      sym_cue_name,
      ts_builtin_sym_end,
      sym__line_terminator,
  [790] = 3,
    ACTIONS(202), 1,
      sym_cue_setting_item,
    ACTIONS(204), 1,
      sym__line_terminator,
    STATE(45), 2,
      sym_cue_setting,
      aux_sym_cue_settings_repeat1,
  [801] = 3,
    ACTIONS(202), 1,
      sym_cue_setting_item,
    ACTIONS(206), 1,
      sym__line_terminator,
    STATE(46), 2,
      sym_cue_setting,
      aux_sym_cue_settings_repeat1,
  [812] = 3,
    ACTIONS(208), 1,
      sym_cue_setting_item,
    ACTIONS(211), 1,
      sym__line_terminator,
    STATE(46), 2,
      sym_cue_setting,
      aux_sym_cue_settings_repeat1,
  [823] = 4,
    ACTIONS(213), 1,
      sym_tab_separator,
    ACTIONS(215), 1,
      sym_space_separator,
    STATE(67), 1,
      aux_sym_timestamp_range_line_repeat1,
    STATE(68), 1,
      aux_sym_timestamp_range_line_repeat2,
  [836] = 3,
    ACTIONS(217), 1,
      sym__line_terminator,
    ACTIONS(219), 1,
      sym_line_without_arrow,
    STATE(63), 1,
      aux_sym_comment_block_repeat1,
  [846] = 3,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(221), 1,
      sym__line_terminator,
    STATE(49), 1,
      aux_sym_source_file_repeat2,
  [856] = 3,
    ACTIONS(224), 1,
      sym__line_terminator,
    ACTIONS(226), 1,
      sym_line_without_arrow,
    STATE(57), 1,
      aux_sym_comment_block_repeat1,
  [866] = 3,
    ACTIONS(219), 1,
      sym_line_without_arrow,
    ACTIONS(228), 1,
      sym__line_terminator,
    STATE(63), 1,
      aux_sym_comment_block_repeat1,
  [876] = 3,
    ACTIONS(219), 1,
      sym_line_without_arrow,
    ACTIONS(230), 1,
      sym__line_terminator,
    STATE(63), 1,
      aux_sym_comment_block_repeat1,
  [886] = 3,
    ACTIONS(232), 1,
      sym_space_separator,
    ACTIONS(235), 1,
      sym_timestamp_arrow,
    STATE(53), 1,
      aux_sym_timestamp_range_line_repeat1,
  [896] = 3,
    ACTIONS(237), 1,
      sym_tab_separator,
    ACTIONS(240), 1,
      sym_timestamp_arrow,
    STATE(54), 1,
      aux_sym_timestamp_range_line_repeat2,
  [906] = 2,
    ACTIONS(244), 1,
      sym__line_terminator,
    ACTIONS(242), 2,
      sym_tab_separator,
      sym_space_separator,
  [914] = 3,
    ACTIONS(246), 1,
      sym__line_terminator,
    ACTIONS(248), 1,
      sym_line_without_arrow,
    STATE(52), 1,
      aux_sym_comment_block_repeat1,
  [924] = 3,
    ACTIONS(219), 1,
      sym_line_without_arrow,
    ACTIONS(250), 1,
      sym__line_terminator,
    STATE(63), 1,
      aux_sym_comment_block_repeat1,
  [934] = 3,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(252), 1,
      sym__line_terminator,
    STATE(49), 1,
      aux_sym_source_file_repeat2,
  [944] = 2,
    ACTIONS(256), 1,
      sym__line_terminator,
    ACTIONS(254), 2,
      sym_tab_separator,
      sym_space_separator,
  [952] = 3,
    ACTIONS(258), 1,
      sym_tabs_or_spaces,
    ACTIONS(260), 1,
      sym__line_terminator,
    STATE(91), 1,
      sym_cue_settings,
  [962] = 3,
    ACTIONS(219), 1,
      sym_line_without_arrow,
    ACTIONS(262), 1,
      sym__line_terminator,
    STATE(63), 1,
      aux_sym_comment_block_repeat1,
  [972] = 3,
    ACTIONS(262), 1,
      sym__line_terminator,
    ACTIONS(264), 1,
      sym_line_without_arrow,
    STATE(48), 1,
      aux_sym_comment_block_repeat1,
  [982] = 3,
    ACTIONS(266), 1,
      sym__line_terminator,
    ACTIONS(268), 1,
      sym_line_without_arrow,
    STATE(63), 1,
      aux_sym_comment_block_repeat1,
  [992] = 1,
    ACTIONS(271), 3,
      sym_tab_separator,
      sym_space_separator,
      sym__line_terminator,
  [998] = 3,
    ACTIONS(252), 1,
      sym__line_terminator,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
    STATE(49), 1,
      aux_sym_source_file_repeat2,
  [1008] = 3,
    ACTIONS(275), 1,
      sym__line_terminator,
    ACTIONS(277), 1,
      sym_line_without_arrow,
    STATE(51), 1,
      aux_sym_comment_block_repeat1,
  [1018] = 3,
    ACTIONS(279), 1,
      sym_space_separator,
    ACTIONS(281), 1,
      sym_timestamp_arrow,
    STATE(53), 1,
      aux_sym_timestamp_range_line_repeat1,
  [1028] = 3,
    ACTIONS(281), 1,
      sym_timestamp_arrow,
    ACTIONS(283), 1,
      sym_tab_separator,
    STATE(54), 1,
      aux_sym_timestamp_range_line_repeat2,
  [1038] = 3,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(252), 1,
      sym__line_terminator,
    STATE(49), 1,
      aux_sym_source_file_repeat2,
  [1048] = 3,
    ACTIONS(258), 1,
      sym_tabs_or_spaces,
    ACTIONS(285), 1,
      sym__line_terminator,
    STATE(84), 1,
      sym_cue_settings,
  [1058] = 3,
    ACTIONS(250), 1,
      sym__line_terminator,
    ACTIONS(287), 1,
      sym_line_without_arrow,
    STATE(61), 1,
      aux_sym_comment_block_repeat1,
  [1068] = 1,
    ACTIONS(289), 2,
      sym_tabs_or_spaces,
      sym__line_terminator,
  [1073] = 2,
    ACTIONS(291), 1,
      sym_timestamp,
    STATE(60), 1,
      sym_timestamp_range_line,
  [1080] = 1,
    ACTIONS(293), 2,
      sym_cue_setting_item,
      sym__line_terminator,
  [1085] = 2,
    ACTIONS(295), 1,
      sym_tabs_or_spaces,
    ACTIONS(297), 1,
      sym__line_terminator,
  [1092] = 1,
    ACTIONS(299), 1,
      sym_line_without_arrow,
  [1096] = 1,
    ACTIONS(301), 1,
      sym_line_without_arrow,
  [1100] = 1,
    ACTIONS(303), 1,
      sym_line_without_arrow,
  [1104] = 1,
    ACTIONS(305), 1,
      sym_line_without_arrow,
  [1108] = 1,
    ACTIONS(307), 1,
      sym__line_terminator,
  [1112] = 1,
    ACTIONS(309), 1,
      sym_line_without_arrow,
  [1116] = 1,
    ACTIONS(311), 1,
      sym_line_without_arrow,
  [1120] = 1,
    ACTIONS(313), 1,
      sym__line_terminator,
  [1124] = 1,
    ACTIONS(315), 1,
      sym__line_terminator,
  [1128] = 1,
    ACTIONS(317), 1,
      sym__line_terminator,
  [1132] = 1,
    ACTIONS(319), 1,
      sym_separator_colon,
  [1136] = 1,
    ACTIONS(321), 1,
      sym_cue_setting_item,
  [1140] = 1,
    ACTIONS(323), 1,
      sym_line_without_arrow,
  [1144] = 1,
    ACTIONS(325), 1,
      sym_separator_colon,
  [1148] = 1,
    ACTIONS(327), 1,
      sym_separator_colon,
  [1152] = 1,
    ACTIONS(329), 1,
      sym__line_terminator,
  [1156] = 1,
    ACTIONS(331), 1,
      sym_separator_colon,
  [1160] = 1,
    ACTIONS(333), 1,
      sym_timestamp,
  [1164] = 1,
    ACTIONS(335), 1,
      sym_separator_colon,
  [1168] = 1,
    ACTIONS(337), 1,
      sym__line_terminator,
  [1172] = 1,
    ACTIONS(339), 1,
      sym_line_without_arrow,
  [1176] = 1,
    ACTIONS(341), 1,
      ts_builtin_sym_end,
  [1180] = 1,
    ACTIONS(343), 1,
      sym_webvtt_keyword,
  [1184] = 1,
    ACTIONS(345), 1,
      sym_separator_colon,
  [1188] = 1,
    ACTIONS(347), 1,
      sym_separator_colon,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 235,
  [SMALL_STATE(10)] = 260,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 344,
  [SMALL_STATE(14)] = 372,
  [SMALL_STATE(15)] = 400,
  [SMALL_STATE(16)] = 423,
  [SMALL_STATE(17)] = 438,
  [SMALL_STATE(18)] = 453,
  [SMALL_STATE(19)] = 468,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 500,
  [SMALL_STATE(22)] = 515,
  [SMALL_STATE(23)] = 530,
  [SMALL_STATE(24)] = 545,
  [SMALL_STATE(25)] = 560,
  [SMALL_STATE(26)] = 572,
  [SMALL_STATE(27)] = 584,
  [SMALL_STATE(28)] = 596,
  [SMALL_STATE(29)] = 608,
  [SMALL_STATE(30)] = 620,
  [SMALL_STATE(31)] = 632,
  [SMALL_STATE(32)] = 644,
  [SMALL_STATE(33)] = 656,
  [SMALL_STATE(34)] = 668,
  [SMALL_STATE(35)] = 680,
  [SMALL_STATE(36)] = 692,
  [SMALL_STATE(37)] = 704,
  [SMALL_STATE(38)] = 716,
  [SMALL_STATE(39)] = 733,
  [SMALL_STATE(40)] = 750,
  [SMALL_STATE(41)] = 760,
  [SMALL_STATE(42)] = 770,
  [SMALL_STATE(43)] = 780,
  [SMALL_STATE(44)] = 790,
  [SMALL_STATE(45)] = 801,
  [SMALL_STATE(46)] = 812,
  [SMALL_STATE(47)] = 823,
  [SMALL_STATE(48)] = 836,
  [SMALL_STATE(49)] = 846,
  [SMALL_STATE(50)] = 856,
  [SMALL_STATE(51)] = 866,
  [SMALL_STATE(52)] = 876,
  [SMALL_STATE(53)] = 886,
  [SMALL_STATE(54)] = 896,
  [SMALL_STATE(55)] = 906,
  [SMALL_STATE(56)] = 914,
  [SMALL_STATE(57)] = 924,
  [SMALL_STATE(58)] = 934,
  [SMALL_STATE(59)] = 944,
  [SMALL_STATE(60)] = 952,
  [SMALL_STATE(61)] = 962,
  [SMALL_STATE(62)] = 972,
  [SMALL_STATE(63)] = 982,
  [SMALL_STATE(64)] = 992,
  [SMALL_STATE(65)] = 998,
  [SMALL_STATE(66)] = 1008,
  [SMALL_STATE(67)] = 1018,
  [SMALL_STATE(68)] = 1028,
  [SMALL_STATE(69)] = 1038,
  [SMALL_STATE(70)] = 1048,
  [SMALL_STATE(71)] = 1058,
  [SMALL_STATE(72)] = 1068,
  [SMALL_STATE(73)] = 1073,
  [SMALL_STATE(74)] = 1080,
  [SMALL_STATE(75)] = 1085,
  [SMALL_STATE(76)] = 1092,
  [SMALL_STATE(77)] = 1096,
  [SMALL_STATE(78)] = 1100,
  [SMALL_STATE(79)] = 1104,
  [SMALL_STATE(80)] = 1108,
  [SMALL_STATE(81)] = 1112,
  [SMALL_STATE(82)] = 1116,
  [SMALL_STATE(83)] = 1120,
  [SMALL_STATE(84)] = 1124,
  [SMALL_STATE(85)] = 1128,
  [SMALL_STATE(86)] = 1132,
  [SMALL_STATE(87)] = 1136,
  [SMALL_STATE(88)] = 1140,
  [SMALL_STATE(89)] = 1144,
  [SMALL_STATE(90)] = 1148,
  [SMALL_STATE(91)] = 1152,
  [SMALL_STATE(92)] = 1156,
  [SMALL_STATE(93)] = 1160,
  [SMALL_STATE(94)] = 1164,
  [SMALL_STATE(95)] = 1168,
  [SMALL_STATE(96)] = 1172,
  [SMALL_STATE(97)] = 1176,
  [SMALL_STATE(98)] = 1180,
  [SMALL_STATE(99)] = 1184,
  [SMALL_STATE(100)] = 1188,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(64),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(47),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(73),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(20),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 5, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 5, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 6, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 6, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_block, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_scroll, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_scroll, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_width, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_width, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_definition_block, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_definition_block, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_block, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_block, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_lines, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_lines, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_definition_block, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_definition_block, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_block, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_block, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_block, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_definition_block, 5, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_definition_block, 5, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_identifier, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_identifier, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_anchor, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_anchor, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_viewport_anchor, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_viewport_anchor, 3, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), REDUCE(sym_source_file, 3, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), REDUCE(sym_source_file, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_block, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 6, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_block, 6, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_block, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 5, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_block, 5, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_settings, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_settings, 2, 0, 0),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_settings_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_settings_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(49),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_timestamp_range_line_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_timestamp_range_line_repeat1, 2, 0, 0),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_timestamp_range_line_repeat2, 2, 0, 0), SHIFT_REPEAT(54),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_timestamp_range_line_repeat2, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 0),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timestamp_range_line, 4, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_setting, 3, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [341] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_line_without_arrow = 0,
  ts_external_token_cue_name = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_line_without_arrow] = sym_line_without_arrow,
  [ts_external_token_cue_name] = sym_cue_name,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_line_without_arrow] = true,
    [ts_external_token_cue_name] = true,
  },
  [2] = {
    [ts_external_token_cue_name] = true,
  },
  [3] = {
    [ts_external_token_line_without_arrow] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_webvtt_external_scanner_create(void);
void tree_sitter_webvtt_external_scanner_destroy(void *);
bool tree_sitter_webvtt_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_webvtt_external_scanner_serialize(void *, char *);
void tree_sitter_webvtt_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_webvtt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_webvtt_external_scanner_create,
      tree_sitter_webvtt_external_scanner_destroy,
      tree_sitter_webvtt_external_scanner_scan,
      tree_sitter_webvtt_external_scanner_serialize,
      tree_sitter_webvtt_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "webvtt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
