/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_webvtt_block_token1 = 1,
  anon_sym_REGION = 2,
  anon_sym_id = 3,
  anon_sym_width = 4,
  anon_sym_lines = 5,
  anon_sym_regionanchor = 6,
  anon_sym_viewportanchor = 7,
  anon_sym_scroll = 8,
  anon_sym_NOTE = 9,
  anon_sym_STYLE = 10,
  sym_byte_order_mark = 11,
  sym_cue_setting_item = 12,
  sym_separator_colon = 13,
  sym_tab_separator = 14,
  sym_space_separator = 15,
  sym_tabs_or_spaces = 16,
  sym_line_terminator = 17,
  sym_timestamp = 18,
  sym_timestamp_arrow = 19,
  sym_line_without_arrow = 20,
  sym_cue_name = 21,
  sym_source_file = 22,
  sym_items = 23,
  sym_webvtt_block = 24,
  sym_region_definition_block = 25,
  sym_region_identifier = 26,
  sym_region_width = 27,
  sym_region_lines = 28,
  sym_region_anchor = 29,
  sym_region_viewport_anchor = 30,
  sym_region_scroll = 31,
  sym_comment_block = 32,
  sym_style_block = 33,
  sym_cue_block = 34,
  sym_cue_settings = 35,
  sym_cue_setting = 36,
  sym_timestamp_range_line = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_webvtt_block_repeat1 = 39,
  aux_sym_region_definition_block_repeat1 = 40,
  aux_sym_comment_block_repeat1 = 41,
  aux_sym_cue_settings_repeat1 = 42,
  aux_sym_timestamp_range_line_repeat1 = 43,
  aux_sym_timestamp_range_line_repeat2 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_webvtt_block_token1] = "webvtt_block_token1",
  [anon_sym_REGION] = "REGION",
  [anon_sym_id] = "id",
  [anon_sym_width] = "width",
  [anon_sym_lines] = "lines",
  [anon_sym_regionanchor] = "regionanchor",
  [anon_sym_viewportanchor] = "viewportanchor",
  [anon_sym_scroll] = "scroll",
  [anon_sym_NOTE] = "NOTE",
  [anon_sym_STYLE] = "STYLE",
  [sym_byte_order_mark] = "byte_order_mark",
  [sym_cue_setting_item] = "cue_setting_item",
  [sym_separator_colon] = "separator_colon",
  [sym_tab_separator] = "tab_separator",
  [sym_space_separator] = "space_separator",
  [sym_tabs_or_spaces] = "tabs_or_spaces",
  [sym_line_terminator] = "line_terminator",
  [sym_timestamp] = "timestamp",
  [sym_timestamp_arrow] = "timestamp_arrow",
  [sym_line_without_arrow] = "line_without_arrow",
  [sym_cue_name] = "cue_name",
  [sym_source_file] = "source_file",
  [sym_items] = "items",
  [sym_webvtt_block] = "webvtt_block",
  [sym_region_definition_block] = "region_definition_block",
  [sym_region_identifier] = "region_identifier",
  [sym_region_width] = "region_width",
  [sym_region_lines] = "region_lines",
  [sym_region_anchor] = "region_anchor",
  [sym_region_viewport_anchor] = "region_viewport_anchor",
  [sym_region_scroll] = "region_scroll",
  [sym_comment_block] = "comment_block",
  [sym_style_block] = "style_block",
  [sym_cue_block] = "cue_block",
  [sym_cue_settings] = "cue_settings",
  [sym_cue_setting] = "cue_setting",
  [sym_timestamp_range_line] = "timestamp_range_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_webvtt_block_repeat1] = "webvtt_block_repeat1",
  [aux_sym_region_definition_block_repeat1] = "region_definition_block_repeat1",
  [aux_sym_comment_block_repeat1] = "comment_block_repeat1",
  [aux_sym_cue_settings_repeat1] = "cue_settings_repeat1",
  [aux_sym_timestamp_range_line_repeat1] = "timestamp_range_line_repeat1",
  [aux_sym_timestamp_range_line_repeat2] = "timestamp_range_line_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_webvtt_block_token1] = aux_sym_webvtt_block_token1,
  [anon_sym_REGION] = anon_sym_REGION,
  [anon_sym_id] = anon_sym_id,
  [anon_sym_width] = anon_sym_width,
  [anon_sym_lines] = anon_sym_lines,
  [anon_sym_regionanchor] = anon_sym_regionanchor,
  [anon_sym_viewportanchor] = anon_sym_viewportanchor,
  [anon_sym_scroll] = anon_sym_scroll,
  [anon_sym_NOTE] = anon_sym_NOTE,
  [anon_sym_STYLE] = anon_sym_STYLE,
  [sym_byte_order_mark] = sym_byte_order_mark,
  [sym_cue_setting_item] = sym_cue_setting_item,
  [sym_separator_colon] = sym_separator_colon,
  [sym_tab_separator] = sym_tab_separator,
  [sym_space_separator] = sym_space_separator,
  [sym_tabs_or_spaces] = sym_tabs_or_spaces,
  [sym_line_terminator] = sym_line_terminator,
  [sym_timestamp] = sym_timestamp,
  [sym_timestamp_arrow] = sym_timestamp_arrow,
  [sym_line_without_arrow] = sym_line_without_arrow,
  [sym_cue_name] = sym_cue_name,
  [sym_source_file] = sym_source_file,
  [sym_items] = sym_items,
  [sym_webvtt_block] = sym_webvtt_block,
  [sym_region_definition_block] = sym_region_definition_block,
  [sym_region_identifier] = sym_region_identifier,
  [sym_region_width] = sym_region_width,
  [sym_region_lines] = sym_region_lines,
  [sym_region_anchor] = sym_region_anchor,
  [sym_region_viewport_anchor] = sym_region_viewport_anchor,
  [sym_region_scroll] = sym_region_scroll,
  [sym_comment_block] = sym_comment_block,
  [sym_style_block] = sym_style_block,
  [sym_cue_block] = sym_cue_block,
  [sym_cue_settings] = sym_cue_settings,
  [sym_cue_setting] = sym_cue_setting,
  [sym_timestamp_range_line] = sym_timestamp_range_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_webvtt_block_repeat1] = aux_sym_webvtt_block_repeat1,
  [aux_sym_region_definition_block_repeat1] = aux_sym_region_definition_block_repeat1,
  [aux_sym_comment_block_repeat1] = aux_sym_comment_block_repeat1,
  [aux_sym_cue_settings_repeat1] = aux_sym_cue_settings_repeat1,
  [aux_sym_timestamp_range_line_repeat1] = aux_sym_timestamp_range_line_repeat1,
  [aux_sym_timestamp_range_line_repeat2] = aux_sym_timestamp_range_line_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_webvtt_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_REGION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_id] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_width] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lines] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_regionanchor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_viewportanchor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scroll] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STYLE] = {
    .visible = true,
    .named = false,
  },
  [sym_byte_order_mark] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_setting_item] = {
    .visible = true,
    .named = true,
  },
  [sym_separator_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_tab_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_space_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_tabs_or_spaces] = {
    .visible = true,
    .named = true,
  },
  [sym_line_terminator] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_line_without_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_name] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_items] = {
    .visible = true,
    .named = true,
  },
  [sym_webvtt_block] = {
    .visible = true,
    .named = true,
  },
  [sym_region_definition_block] = {
    .visible = true,
    .named = true,
  },
  [sym_region_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_region_width] = {
    .visible = true,
    .named = true,
  },
  [sym_region_lines] = {
    .visible = true,
    .named = true,
  },
  [sym_region_anchor] = {
    .visible = true,
    .named = true,
  },
  [sym_region_viewport_anchor] = {
    .visible = true,
    .named = true,
  },
  [sym_region_scroll] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym_style_block] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_block] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_settings] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp_range_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_webvtt_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_region_definition_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cue_settings_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_timestamp_range_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_timestamp_range_line_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(79);
      ADVANCE_MAP(
        '-', 7,
        ':', 94,
        'N', 24,
        'R', 14,
        'S', 25,
        'W', 17,
        'i', 36,
        'l', 45,
        'r', 38,
        's', 33,
        'v', 47,
        'w', 46,
        0xefbb, 12,
        0xfeff, 90,
        0xfffe, 90,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(95);
      if (lookahead == ' ') ADVANCE(98);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(96);
      if (lookahead == '-') ADVANCE(7);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(104);
      if (lookahead == '\r') ADVANCE(104);
      if (lookahead == ' ') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(100);
      if (lookahead == '-') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(77);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(77);
      if (lookahead == ':') ADVANCE(75);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(74);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(107);
      END_STATE();
    case 12:
      if (lookahead == 'B') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'B') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(88);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(89);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'F') ADVANCE(90);
      END_STATE();
    case 19:
      if (lookahead == 'G') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 'I') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'N') ADVANCE(81);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'T') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'T') ADVANCE(80);
      END_STATE();
    case 27:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 28:
      if (lookahead == 'T') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 'V') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 'Y') ADVANCE(21);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(82);
      END_STATE();
    case 37:
      if (lookahead == 'd') ADVANCE(66);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 41:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 42:
      if (lookahead == 'h') ADVANCE(83);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(58);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(59);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(63);
      END_STATE();
    case 60:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(85);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(84);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 68:
      if (lookahead == 'w') ADVANCE(60);
      END_STATE();
    case 69:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(92);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(69);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 73:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 74:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 75:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 78:
      if (eof) ADVANCE(79);
      ADVANCE_MAP(
        '\n', 103,
        '\r', 103,
        'N', 24,
        'R', 14,
        'S', 25,
        'i', 36,
        'l', 45,
        'r', 38,
        's', 33,
        'v', 47,
        'w', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_webvtt_block_token1);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_REGION);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_id);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_width);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_lines);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_regionanchor);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_viewportanchor);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_scroll);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_NOTE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_STYLE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_byte_order_mark);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_cue_setting_item);
      if (lookahead == '\n') ADVANCE(104);
      if (lookahead == '\r') ADVANCE(104);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_cue_setting_item);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_cue_setting_item);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_separator_colon);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_tab_separator);
      if (lookahead == '\t') ADVANCE(95);
      if (lookahead == ' ') ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_tab_separator);
      if (lookahead == '\t') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_tab_separator);
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_space_separator);
      if (lookahead == '\t') ADVANCE(95);
      if (lookahead == ' ') ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_space_separator);
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_space_separator);
      if (lookahead == ' ') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_tabs_or_spaces);
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_line_terminator);
      if (lookahead == '\t') ADVANCE(97);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_line_terminator);
      if (lookahead == '\n') ADVANCE(103);
      if (lookahead == '\r') ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_line_terminator);
      if (lookahead == '\n') ADVANCE(104);
      if (lookahead == '\r') ADVANCE(104);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(91);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_line_terminator);
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_timestamp);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_timestamp_arrow);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 78},
  [3] = {.lex_state = 78},
  [4] = {.lex_state = 78},
  [5] = {.lex_state = 78},
  [6] = {.lex_state = 78},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 78, .external_lex_state = 2},
  [11] = {.lex_state = 78, .external_lex_state = 2},
  [12] = {.lex_state = 78, .external_lex_state = 2},
  [13] = {.lex_state = 78, .external_lex_state = 2},
  [14] = {.lex_state = 78, .external_lex_state = 2},
  [15] = {.lex_state = 78},
  [16] = {.lex_state = 78},
  [17] = {.lex_state = 78},
  [18] = {.lex_state = 78},
  [19] = {.lex_state = 78},
  [20] = {.lex_state = 78},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 78, .external_lex_state = 3},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 78, .external_lex_state = 3},
  [41] = {.lex_state = 78, .external_lex_state = 3},
  [42] = {.lex_state = 78, .external_lex_state = 3},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 78, .external_lex_state = 3},
  [46] = {.lex_state = 78, .external_lex_state = 3},
  [47] = {.lex_state = 78, .external_lex_state = 3},
  [48] = {.lex_state = 78, .external_lex_state = 3},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 78, .external_lex_state = 3},
  [52] = {.lex_state = 78, .external_lex_state = 3},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 78, .external_lex_state = 3},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 3},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0, .external_lex_state = 3},
  [62] = {.lex_state = 0, .external_lex_state = 3},
  [63] = {.lex_state = 0, .external_lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 78},
  [69] = {.lex_state = 69},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 78},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 78},
  [74] = {.lex_state = 78},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 78},
  [78] = {.lex_state = 78},
  [79] = {.lex_state = 0, .external_lex_state = 3},
  [80] = {.lex_state = 0, .external_lex_state = 3},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_webvtt_block_token1] = ACTIONS(1),
    [anon_sym_REGION] = ACTIONS(1),
    [anon_sym_id] = ACTIONS(1),
    [anon_sym_width] = ACTIONS(1),
    [anon_sym_lines] = ACTIONS(1),
    [anon_sym_regionanchor] = ACTIONS(1),
    [anon_sym_viewportanchor] = ACTIONS(1),
    [anon_sym_scroll] = ACTIONS(1),
    [anon_sym_NOTE] = ACTIONS(1),
    [anon_sym_STYLE] = ACTIONS(1),
    [sym_byte_order_mark] = ACTIONS(1),
    [sym_separator_colon] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
    [sym_timestamp_arrow] = ACTIONS(1),
    [sym_line_without_arrow] = ACTIONS(1),
    [sym_cue_name] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym_webvtt_block] = STATE(7),
    [aux_sym_webvtt_block_token1] = ACTIONS(3),
    [sym_byte_order_mark] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      anon_sym_id,
    ACTIONS(9), 1,
      anon_sym_width,
    ACTIONS(11), 1,
      anon_sym_lines,
    ACTIONS(13), 1,
      anon_sym_regionanchor,
    ACTIONS(15), 1,
      anon_sym_viewportanchor,
    ACTIONS(17), 1,
      anon_sym_scroll,
    ACTIONS(19), 1,
      sym_line_terminator,
    STATE(4), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [31] = 8,
    ACTIONS(7), 1,
      anon_sym_id,
    ACTIONS(9), 1,
      anon_sym_width,
    ACTIONS(11), 1,
      anon_sym_lines,
    ACTIONS(13), 1,
      anon_sym_regionanchor,
    ACTIONS(15), 1,
      anon_sym_viewportanchor,
    ACTIONS(17), 1,
      anon_sym_scroll,
    ACTIONS(21), 1,
      sym_line_terminator,
    STATE(5), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [62] = 8,
    ACTIONS(7), 1,
      anon_sym_id,
    ACTIONS(9), 1,
      anon_sym_width,
    ACTIONS(11), 1,
      anon_sym_lines,
    ACTIONS(13), 1,
      anon_sym_regionanchor,
    ACTIONS(15), 1,
      anon_sym_viewportanchor,
    ACTIONS(17), 1,
      anon_sym_scroll,
    ACTIONS(21), 1,
      sym_line_terminator,
    STATE(6), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [93] = 8,
    ACTIONS(7), 1,
      anon_sym_id,
    ACTIONS(9), 1,
      anon_sym_width,
    ACTIONS(11), 1,
      anon_sym_lines,
    ACTIONS(13), 1,
      anon_sym_regionanchor,
    ACTIONS(15), 1,
      anon_sym_viewportanchor,
    ACTIONS(17), 1,
      anon_sym_scroll,
    ACTIONS(23), 1,
      sym_line_terminator,
    STATE(6), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [124] = 8,
    ACTIONS(25), 1,
      anon_sym_id,
    ACTIONS(28), 1,
      anon_sym_width,
    ACTIONS(31), 1,
      anon_sym_lines,
    ACTIONS(34), 1,
      anon_sym_regionanchor,
    ACTIONS(37), 1,
      anon_sym_viewportanchor,
    ACTIONS(40), 1,
      anon_sym_scroll,
    ACTIONS(43), 1,
      sym_line_terminator,
    STATE(6), 7,
      sym_region_identifier,
      sym_region_width,
      sym_region_lines,
      sym_region_anchor,
      sym_region_viewport_anchor,
      sym_region_scroll,
      aux_sym_region_definition_block_repeat1,
  [155] = 9,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_REGION,
    ACTIONS(49), 1,
      anon_sym_NOTE,
    ACTIONS(51), 1,
      anon_sym_STYLE,
    ACTIONS(53), 1,
      sym_timestamp,
    ACTIONS(55), 1,
      sym_cue_name,
    STATE(49), 1,
      sym_timestamp_range_line,
    STATE(8), 2,
      sym_items,
      aux_sym_source_file_repeat1,
    STATE(23), 4,
      sym_region_definition_block,
      sym_comment_block,
      sym_style_block,
      sym_cue_block,
  [187] = 9,
    ACTIONS(47), 1,
      anon_sym_REGION,
    ACTIONS(49), 1,
      anon_sym_NOTE,
    ACTIONS(51), 1,
      anon_sym_STYLE,
    ACTIONS(53), 1,
      sym_timestamp,
    ACTIONS(55), 1,
      sym_cue_name,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(49), 1,
      sym_timestamp_range_line,
    STATE(9), 2,
      sym_items,
      aux_sym_source_file_repeat1,
    STATE(23), 4,
      sym_region_definition_block,
      sym_comment_block,
      sym_style_block,
      sym_cue_block,
  [219] = 9,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_REGION,
    ACTIONS(64), 1,
      anon_sym_NOTE,
    ACTIONS(67), 1,
      anon_sym_STYLE,
    ACTIONS(70), 1,
      sym_timestamp,
    ACTIONS(73), 1,
      sym_cue_name,
    STATE(49), 1,
      sym_timestamp_range_line,
    STATE(9), 2,
      sym_items,
      aux_sym_source_file_repeat1,
    STATE(23), 4,
      sym_region_definition_block,
      sym_comment_block,
      sym_style_block,
      sym_cue_block,
  [251] = 4,
    ACTIONS(80), 1,
      sym_line_terminator,
    STATE(12), 1,
      aux_sym_webvtt_block_repeat1,
    ACTIONS(76), 2,
      sym_cue_name,
      ts_builtin_sym_end,
    ACTIONS(78), 4,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [268] = 4,
    ACTIONS(86), 1,
      sym_line_terminator,
    STATE(14), 1,
      aux_sym_webvtt_block_repeat1,
    ACTIONS(82), 2,
      sym_cue_name,
      ts_builtin_sym_end,
    ACTIONS(84), 4,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [285] = 4,
    ACTIONS(88), 1,
      sym_line_terminator,
    STATE(13), 1,
      aux_sym_webvtt_block_repeat1,
    ACTIONS(82), 2,
      sym_cue_name,
      ts_builtin_sym_end,
    ACTIONS(84), 4,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [302] = 4,
    ACTIONS(94), 1,
      sym_line_terminator,
    STATE(13), 1,
      aux_sym_webvtt_block_repeat1,
    ACTIONS(90), 2,
      sym_cue_name,
      ts_builtin_sym_end,
    ACTIONS(92), 4,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [319] = 4,
    ACTIONS(88), 1,
      sym_line_terminator,
    STATE(13), 1,
      aux_sym_webvtt_block_repeat1,
    ACTIONS(97), 2,
      sym_cue_name,
      ts_builtin_sym_end,
    ACTIONS(99), 4,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [336] = 2,
    ACTIONS(103), 1,
      sym_line_terminator,
    ACTIONS(101), 6,
      anon_sym_id,
      anon_sym_width,
      anon_sym_lines,
      anon_sym_regionanchor,
      anon_sym_viewportanchor,
      anon_sym_scroll,
  [348] = 2,
    ACTIONS(107), 1,
      sym_line_terminator,
    ACTIONS(105), 6,
      anon_sym_id,
      anon_sym_width,
      anon_sym_lines,
      anon_sym_regionanchor,
      anon_sym_viewportanchor,
      anon_sym_scroll,
  [360] = 2,
    ACTIONS(111), 1,
      sym_line_terminator,
    ACTIONS(109), 6,
      anon_sym_id,
      anon_sym_width,
      anon_sym_lines,
      anon_sym_regionanchor,
      anon_sym_viewportanchor,
      anon_sym_scroll,
  [372] = 2,
    ACTIONS(115), 1,
      sym_line_terminator,
    ACTIONS(113), 6,
      anon_sym_id,
      anon_sym_width,
      anon_sym_lines,
      anon_sym_regionanchor,
      anon_sym_viewportanchor,
      anon_sym_scroll,
  [384] = 2,
    ACTIONS(119), 1,
      sym_line_terminator,
    ACTIONS(117), 6,
      anon_sym_id,
      anon_sym_width,
      anon_sym_lines,
      anon_sym_regionanchor,
      anon_sym_viewportanchor,
      anon_sym_scroll,
  [396] = 2,
    ACTIONS(123), 1,
      sym_line_terminator,
    ACTIONS(121), 6,
      anon_sym_id,
      anon_sym_width,
      anon_sym_lines,
      anon_sym_regionanchor,
      anon_sym_viewportanchor,
      anon_sym_scroll,
  [408] = 1,
    ACTIONS(125), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [417] = 1,
    ACTIONS(127), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [426] = 1,
    ACTIONS(129), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [435] = 1,
    ACTIONS(131), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [444] = 1,
    ACTIONS(133), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [453] = 1,
    ACTIONS(135), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [462] = 1,
    ACTIONS(137), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [471] = 1,
    ACTIONS(139), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [480] = 1,
    ACTIONS(141), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [489] = 1,
    ACTIONS(143), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [498] = 1,
    ACTIONS(145), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [507] = 1,
    ACTIONS(147), 6,
      sym_cue_name,
      ts_builtin_sym_end,
      anon_sym_REGION,
      anon_sym_NOTE,
      anon_sym_STYLE,
      sym_timestamp,
  [516] = 3,
    ACTIONS(149), 1,
      sym_cue_setting_item,
    ACTIONS(151), 1,
      sym_line_terminator,
    STATE(34), 2,
      sym_cue_setting,
      aux_sym_cue_settings_repeat1,
  [527] = 3,
    ACTIONS(153), 1,
      sym_cue_setting_item,
    ACTIONS(156), 1,
      sym_line_terminator,
    STATE(34), 2,
      sym_cue_setting,
      aux_sym_cue_settings_repeat1,
  [538] = 4,
    ACTIONS(158), 1,
      sym_tab_separator,
    ACTIONS(160), 1,
      sym_space_separator,
    STATE(37), 1,
      aux_sym_timestamp_range_line_repeat1,
    STATE(39), 1,
      aux_sym_timestamp_range_line_repeat2,
  [551] = 3,
    ACTIONS(149), 1,
      sym_cue_setting_item,
    ACTIONS(162), 1,
      sym_line_terminator,
    STATE(33), 2,
      sym_cue_setting,
      aux_sym_cue_settings_repeat1,
  [562] = 3,
    ACTIONS(164), 1,
      sym_space_separator,
    ACTIONS(166), 1,
      sym_timestamp_arrow,
    STATE(43), 1,
      aux_sym_timestamp_range_line_repeat1,
  [572] = 3,
    ACTIONS(168), 1,
      sym_line_terminator,
    ACTIONS(170), 1,
      sym_line_without_arrow,
    STATE(41), 1,
      aux_sym_comment_block_repeat1,
  [582] = 3,
    ACTIONS(166), 1,
      sym_timestamp_arrow,
    ACTIONS(172), 1,
      sym_tab_separator,
    STATE(44), 1,
      aux_sym_timestamp_range_line_repeat2,
  [592] = 3,
    ACTIONS(174), 1,
      sym_line_terminator,
    ACTIONS(176), 1,
      sym_line_without_arrow,
    STATE(48), 1,
      aux_sym_comment_block_repeat1,
  [602] = 3,
    ACTIONS(176), 1,
      sym_line_without_arrow,
    ACTIONS(178), 1,
      sym_line_terminator,
    STATE(48), 1,
      aux_sym_comment_block_repeat1,
  [612] = 3,
    ACTIONS(176), 1,
      sym_line_without_arrow,
    ACTIONS(180), 1,
      sym_line_terminator,
    STATE(48), 1,
      aux_sym_comment_block_repeat1,
  [622] = 3,
    ACTIONS(182), 1,
      sym_space_separator,
    ACTIONS(185), 1,
      sym_timestamp_arrow,
    STATE(43), 1,
      aux_sym_timestamp_range_line_repeat1,
  [632] = 3,
    ACTIONS(187), 1,
      sym_tab_separator,
    ACTIONS(190), 1,
      sym_timestamp_arrow,
    STATE(44), 1,
      aux_sym_timestamp_range_line_repeat2,
  [642] = 3,
    ACTIONS(192), 1,
      sym_line_terminator,
    ACTIONS(194), 1,
      sym_line_without_arrow,
    STATE(42), 1,
      aux_sym_comment_block_repeat1,
  [652] = 3,
    ACTIONS(176), 1,
      sym_line_without_arrow,
    ACTIONS(196), 1,
      sym_line_terminator,
    STATE(48), 1,
      aux_sym_comment_block_repeat1,
  [662] = 3,
    ACTIONS(196), 1,
      sym_line_terminator,
    ACTIONS(198), 1,
      sym_line_without_arrow,
    STATE(52), 1,
      aux_sym_comment_block_repeat1,
  [672] = 3,
    ACTIONS(200), 1,
      sym_line_terminator,
    ACTIONS(202), 1,
      sym_line_without_arrow,
    STATE(48), 1,
      aux_sym_comment_block_repeat1,
  [682] = 3,
    ACTIONS(205), 1,
      sym_tabs_or_spaces,
    ACTIONS(207), 1,
      sym_line_terminator,
    STATE(68), 1,
      sym_cue_settings,
  [692] = 1,
    ACTIONS(209), 3,
      sym_tab_separator,
      sym_space_separator,
      sym_line_terminator,
  [698] = 3,
    ACTIONS(178), 1,
      sym_line_terminator,
    ACTIONS(211), 1,
      sym_line_without_arrow,
    STATE(46), 1,
      aux_sym_comment_block_repeat1,
  [708] = 3,
    ACTIONS(176), 1,
      sym_line_without_arrow,
    ACTIONS(213), 1,
      sym_line_terminator,
    STATE(48), 1,
      aux_sym_comment_block_repeat1,
  [718] = 3,
    ACTIONS(205), 1,
      sym_tabs_or_spaces,
    ACTIONS(215), 1,
      sym_line_terminator,
    STATE(71), 1,
      sym_cue_settings,
  [728] = 3,
    ACTIONS(217), 1,
      sym_line_terminator,
    ACTIONS(219), 1,
      sym_line_without_arrow,
    STATE(40), 1,
      aux_sym_comment_block_repeat1,
  [738] = 1,
    ACTIONS(221), 2,
      sym_cue_setting_item,
      sym_line_terminator,
  [743] = 2,
    ACTIONS(53), 1,
      sym_timestamp,
    STATE(53), 1,
      sym_timestamp_range_line,
  [750] = 2,
    ACTIONS(223), 1,
      sym_tabs_or_spaces,
    ACTIONS(225), 1,
      sym_line_terminator,
  [757] = 1,
    ACTIONS(227), 2,
      sym_tabs_or_spaces,
      sym_line_terminator,
  [762] = 1,
    ACTIONS(229), 1,
      sym_line_without_arrow,
  [766] = 1,
    ACTIONS(231), 1,
      sym_separator_colon,
  [770] = 1,
    ACTIONS(233), 1,
      sym_line_without_arrow,
  [774] = 1,
    ACTIONS(235), 1,
      sym_line_without_arrow,
  [778] = 1,
    ACTIONS(237), 1,
      sym_line_without_arrow,
  [782] = 1,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
  [786] = 1,
    ACTIONS(241), 1,
      sym_separator_colon,
  [790] = 1,
    ACTIONS(243), 1,
      sym_separator_colon,
  [794] = 1,
    ACTIONS(245), 1,
      sym_timestamp,
  [798] = 1,
    ACTIONS(247), 1,
      sym_line_terminator,
  [802] = 1,
    ACTIONS(249), 1,
      sym_cue_setting_item,
  [806] = 1,
    ACTIONS(251), 1,
      sym_separator_colon,
  [810] = 1,
    ACTIONS(253), 1,
      sym_line_terminator,
  [814] = 1,
    ACTIONS(255), 1,
      sym_separator_colon,
  [818] = 1,
    ACTIONS(257), 1,
      sym_line_terminator,
  [822] = 1,
    ACTIONS(259), 1,
      sym_line_terminator,
  [826] = 1,
    ACTIONS(261), 1,
      aux_sym_webvtt_block_token1,
  [830] = 1,
    ACTIONS(263), 1,
      sym_separator_colon,
  [834] = 1,
    ACTIONS(265), 1,
      sym_line_terminator,
  [838] = 1,
    ACTIONS(267), 1,
      sym_line_terminator,
  [842] = 1,
    ACTIONS(269), 1,
      sym_line_without_arrow,
  [846] = 1,
    ACTIONS(271), 1,
      sym_line_without_arrow,
  [850] = 1,
    ACTIONS(273), 1,
      sym_separator_colon,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 155,
  [SMALL_STATE(8)] = 187,
  [SMALL_STATE(9)] = 219,
  [SMALL_STATE(10)] = 251,
  [SMALL_STATE(11)] = 268,
  [SMALL_STATE(12)] = 285,
  [SMALL_STATE(13)] = 302,
  [SMALL_STATE(14)] = 319,
  [SMALL_STATE(15)] = 336,
  [SMALL_STATE(16)] = 348,
  [SMALL_STATE(17)] = 360,
  [SMALL_STATE(18)] = 372,
  [SMALL_STATE(19)] = 384,
  [SMALL_STATE(20)] = 396,
  [SMALL_STATE(21)] = 408,
  [SMALL_STATE(22)] = 417,
  [SMALL_STATE(23)] = 426,
  [SMALL_STATE(24)] = 435,
  [SMALL_STATE(25)] = 444,
  [SMALL_STATE(26)] = 453,
  [SMALL_STATE(27)] = 462,
  [SMALL_STATE(28)] = 471,
  [SMALL_STATE(29)] = 480,
  [SMALL_STATE(30)] = 489,
  [SMALL_STATE(31)] = 498,
  [SMALL_STATE(32)] = 507,
  [SMALL_STATE(33)] = 516,
  [SMALL_STATE(34)] = 527,
  [SMALL_STATE(35)] = 538,
  [SMALL_STATE(36)] = 551,
  [SMALL_STATE(37)] = 562,
  [SMALL_STATE(38)] = 572,
  [SMALL_STATE(39)] = 582,
  [SMALL_STATE(40)] = 592,
  [SMALL_STATE(41)] = 602,
  [SMALL_STATE(42)] = 612,
  [SMALL_STATE(43)] = 622,
  [SMALL_STATE(44)] = 632,
  [SMALL_STATE(45)] = 642,
  [SMALL_STATE(46)] = 652,
  [SMALL_STATE(47)] = 662,
  [SMALL_STATE(48)] = 672,
  [SMALL_STATE(49)] = 682,
  [SMALL_STATE(50)] = 692,
  [SMALL_STATE(51)] = 698,
  [SMALL_STATE(52)] = 708,
  [SMALL_STATE(53)] = 718,
  [SMALL_STATE(54)] = 728,
  [SMALL_STATE(55)] = 738,
  [SMALL_STATE(56)] = 743,
  [SMALL_STATE(57)] = 750,
  [SMALL_STATE(58)] = 757,
  [SMALL_STATE(59)] = 762,
  [SMALL_STATE(60)] = 766,
  [SMALL_STATE(61)] = 770,
  [SMALL_STATE(62)] = 774,
  [SMALL_STATE(63)] = 778,
  [SMALL_STATE(64)] = 782,
  [SMALL_STATE(65)] = 786,
  [SMALL_STATE(66)] = 790,
  [SMALL_STATE(67)] = 794,
  [SMALL_STATE(68)] = 798,
  [SMALL_STATE(69)] = 802,
  [SMALL_STATE(70)] = 806,
  [SMALL_STATE(71)] = 810,
  [SMALL_STATE(72)] = 814,
  [SMALL_STATE(73)] = 818,
  [SMALL_STATE(74)] = 822,
  [SMALL_STATE(75)] = 826,
  [SMALL_STATE(76)] = 830,
  [SMALL_STATE(77)] = 834,
  [SMALL_STATE(78)] = 838,
  [SMALL_STATE(79)] = 842,
  [SMALL_STATE(80)] = 846,
  [SMALL_STATE(81)] = 850,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_region_definition_block_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_webvtt_block_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_webvtt_block_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_webvtt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt_block, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_webvtt_block, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_identifier, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_identifier, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_width, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_width, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_lines, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_lines, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_anchor, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_anchor, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_viewport_anchor, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_viewport_anchor, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_region_scroll, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_scroll, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_definition_block, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 6, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_items, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_block, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_definition_block, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_block, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_block, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region_definition_block, 5, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_settings, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_settings_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_settings_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_settings, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_timestamp_range_line_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_timestamp_range_line_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_timestamp_range_line_repeat2, 2, 0, 0), SHIFT_REPEAT(44),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_timestamp_range_line_repeat2, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_setting, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timestamp_range_line, 4, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [239] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_line_without_arrow = 0,
  ts_external_token_cue_name = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_line_without_arrow] = sym_line_without_arrow,
  [ts_external_token_cue_name] = sym_cue_name,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_line_without_arrow] = true,
    [ts_external_token_cue_name] = true,
  },
  [2] = {
    [ts_external_token_cue_name] = true,
  },
  [3] = {
    [ts_external_token_line_without_arrow] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_webvtt_external_scanner_create(void);
void tree_sitter_webvtt_external_scanner_destroy(void *);
bool tree_sitter_webvtt_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_webvtt_external_scanner_serialize(void *, char *);
void tree_sitter_webvtt_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_webvtt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_webvtt_external_scanner_create,
      tree_sitter_webvtt_external_scanner_destroy,
      tree_sitter_webvtt_external_scanner_scan,
      tree_sitter_webvtt_external_scanner_serialize,
      tree_sitter_webvtt_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "webvtt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
